/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 39u3HjpCsMgMzencpSSb5j

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsgcz3MWFu0Mn } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: GCZ3mW_FU0Mn/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsgcz3MWFu0Mn
});
